### PR TITLE
Improve CI build time

### PR DESCRIPTION
**Pull request by dhoeric**
For issue #21

### CODE REVIEW

**Comment by wgranados** [comment]
Looks like the builds are failing due to the api keys, but that's really a non-issue. Otherwise looks good!

**Comment by wgranados** [comment]
Thanks!

**Comment by dhoeric** [comment]
@wgma00 Just to remind that building your own base image from `Dockerfile.base` and update on `Dockerfile`. 

After that, I will delete `dhoeric/quadbot-base`.

**Comment by wgranados** [comment]
Alright, working on it

**Comment by wgranados** [comment]
Okay it's done. You can delete it now @dhoeric

**Pull request merged**
